"""users, PriceHistory, Transactions History, Companies

Revision ID: 67b8edee8b67
Revises: 
Create Date: 2020-09-21 16:16:09.649666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67b8edee8b67'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_table('transactions_summary')
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.alter_column('companies', 'scrip',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('companies', 'sector',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('companies', 'ticker',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.create_index(op.f('ix_companies_scrip'), 'companies', ['scrip'], unique=True)
    op.create_index(op.f('ix_companies_sector'), 'companies', ['sector'], unique=False)
    op.create_index(op.f('ix_companies_ticker'), 'companies', ['ticker'], unique=True)
    op.create_index(op.f('ix_price_history_company'), 'price_history', ['company'], unique=False)
    op.create_index(op.f('ix_price_history_date'), 'price_history', ['date'], unique=False)
    op.drop_constraint('unique_day_company', 'price_history', type_='unique')
    op.add_column('transactions_history', sa.Column('buyer_broker', sa.Integer(), nullable=True))
    op.add_column('transactions_history', sa.Column('seller_broker', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_transactions_history_contract_number'), 'transactions_history', ['contract_number'], unique=False)
    op.create_index(op.f('ix_transactions_history_date'), 'transactions_history', ['date'], unique=False)
    op.create_index(op.f('ix_transactions_history_symbol'), 'transactions_history', ['symbol'], unique=False)
    op.drop_column('transactions_history', 'seller')
    op.drop_column('transactions_history', 'buyer')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions_history', sa.Column('buyer', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('transactions_history', sa.Column('seller', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_transactions_history_symbol'), table_name='transactions_history')
    op.drop_index(op.f('ix_transactions_history_date'), table_name='transactions_history')
    op.drop_index(op.f('ix_transactions_history_contract_number'), table_name='transactions_history')
    op.drop_column('transactions_history', 'seller_broker')
    op.drop_column('transactions_history', 'buyer_broker')
    op.create_unique_constraint('unique_day_company', 'price_history', ['date', 'company'])
    op.drop_index(op.f('ix_price_history_date'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_company'), table_name='price_history')
    op.drop_index(op.f('ix_companies_ticker'), table_name='companies')
    op.drop_index(op.f('ix_companies_sector'), table_name='companies')
    op.drop_index(op.f('ix_companies_scrip'), table_name='companies')
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.alter_column('companies', 'ticker',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('companies', 'sector',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('companies', 'scrip',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('companies', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.create_table('transactions_summary',
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('total_amount', sa.NUMERIC(precision=20, scale=2), autoincrement=False, nullable=True),
    sa.Column('total_txns', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('total_quantity', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('date', name='transactions_summary_pkey')
    )
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
